# Site wide configuration

title:            Civility and Truth
locale:           en_US
url:


# Jekyll configuration

permalink:   /:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Frank Hecker
  avatar: bio-photo.jpg
  bio: "Resident of Ellicott City and Howard County, Maryland, systems engineer, and occasional blogger."
  email: frank@frankhecker.com
  disqus-shortname: 
  twitter: hecker
  facebook: frankhecker
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: frankhecker
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
